/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{svelte,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary-fixed-dim": "#bec6e0",
        "primary-container": "#2563eb",
        "on-tertiary-fixed": "#131b2e",
        "secondary-container": "#d0e1fb",
        "background": "#f7f9fb",
        "on-surface-variant": "#434655",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-primary": "#b4c5ff",
        "tertiary-fixed": "#dae2fd",
        "surface": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "primary": "#004ac6",
        "on-secondary-fixed": "#0b1c30",
        "on-primary-container": "#eeefff",
        "outline-variant": "#c3c6d7",
        "tertiary-container": "#656d84",
        "inverse-on-surface": "#eff1f3",
        "secondary": "#505f76",
        "on-primary-fixed-variant": "#003ea8",
        "tertiary": "#4d556b",
        "surface-dim": "#d8dadc",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#eef0ff",
        "primary-fixed": "#dbe1ff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-container": "#eceef0",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fb",
        "on-background": "#191c1e",
        "surface-tint": "#0053db",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "on-tertiary-fixed-variant": "#3f465c",
        "outline": "#737686",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "on-primary-fixed": "#00174b",
        "on-error": "#ffffff",
        "on-secondary-container": "#54647a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "lg": "24px",
        "gutter": "20px",
        "sm": "8px",
        "xs": "4px",
        "base": "4px",
        "xl": "32px",
        "md": "16px",
        "container-max": "1440px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "headline-xl": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"]
      },
      fontSize: {
        "headline-xl": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-lg-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
