-- Flyway Migration V2: Create Dialogs and Messages Tables
CREATE TABLE dialogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_chat_id BIGINT NOT NULL,
    lead_username VARCHAR(255),
    lead_phone VARCHAR(50),
    is_ai_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dialog_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    sender_type VARCHAR(50) NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_dialog_id FOREIGN KEY (dialog_id) REFERENCES dialogs(id) ON DELETE CASCADE,
    CONSTRAINT chk_sender_type CHECK (sender_type IN ('AI', 'HUMAN', 'LEAD'))
);

-- Index for optimization
CREATE INDEX idx_messages_dialog_id ON messages(dialog_id);
